apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: test-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - hosts:
    - "*.homelab.local"
    - homelab.local
    port:
      name: http
      number: 80
      protocol: HTTP