apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: argocd-ingress
spec:
 rules:
 - host: cid.cessmedia.com
   http:
     paths:
     - pathType: Prefix
       path: "/"
       backend:
         service:
           name: argocd-server
           port:
             number: 443